# Generated by Django 5.2.17 on 2026-09-16 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_week3_inventory_ledger'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization'),
        ),
    ]
