# Generated by Django 5.2.17 on 2026-09-22 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_created_by_and_more'),
        ('inventory', '0003_alter_stockadjustment_created_by_and_more'),
        ('tenancy', '0002_alter_user_options_alter_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='fulfilled_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('FULFILLED', 'Fulfilled')], default='ACTIVE', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__gte', 0), ('fulfilled_quantity__lte', models.F('quantity'))), name='reservation_fulfilled_bounds'),
        ),
    ]
