# Generated by Django 5.2.17 on 2026-09-22 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_alter_user_options_alter_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=240)),
                ('category', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('spent_on', models.DateField()),
                ('is_void', models.BooleanField(default=False)),
                ('idempotency_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='expense_key'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_positive')],
            },
        ),
    ]
