# Generated by Django 5.2.17 on 2026-09-23 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenancy', '0002_alter_user_options_alter_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', '-created_at', '-id'], name='audit_org_recent_idx'),
        ),
    ]
