# Generated by Django 5.2.17 on 2026-09-22 16:31

import apps.intelligence.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0002_alter_category_created_by_and_more'),
        ('inventory', '0004_stockreservation_fulfilled_quantity_and_more'),
        ('tenancy', '0002_alter_user_options_alter_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.intelligence.models.private_document_path)),
                ('original_name', models.CharField(max_length=240)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('REVIEW', 'Review'), ('FAILED', 'Failed'), ('APPROVED', 'Approved')], default='UPLOADED', max_length=16)),
                ('extraction', models.JSONField(default=dict)),
                ('correction', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('attempt', models.UUIDField(null=True)),
                ('approval_hash', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inputs', models.JSONField()),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='RUNNING', max_length=16)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
